Small correction in README
spf13/cobra pull request #1009
Opened 2020-01-01 14:01 UTC by NickolasHKraus

I thought this sentence seemed *off*:

> **Note**, that the variable `author` will not be set to the value from config, when the `--author` flag is not provided by user.

In the [Viper documentation](https://github.com/spf13/viper):

> Viper uses the following precedence order. Each item takes precedence over the item below it:
> * explicit call to Set
> * flag
> * env
> * config
> * key/value store
> * default

One would assume that:

> ...the variable `author` will not be set to the value from config, when the `--author` flag *is* provided by user.

Testing with `cobra init` bears this out:

`cobra init --pkg-name test`

```go
/*
Copyright © 2020 Nickolas Kraus

*/
```

`cobra init --pkg-name test --author Me`

```go
/*
Copyright © 2020 Me

*/
```

2020-01-01 14:01 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1009) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cobra?pullRequest=1009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cobra?pullRequest=1009) it.</sub>

2020-01-03 12:09 UTC, NickolasHKraus commented
@umarcor Removed `8994876`. #1010 now contains year bump.

2020-01-04 18:25 UTC, umarcor commented
@NickolasHKraus, thanks! That allowed to rebase many other PRs that failed because of the year.

---

Request to include this PR in [1.0.0](https://github.com/spf13/cobra/milestone/2). Ref #959.

2020-01-06 15:13 UTC, NickolasHKraus commented
@umarcor Anything else required from me on this PR?

2020-01-06 18:20 UTC, umarcor commented
> @umarcor Anything else required from me on this PR?

Now that #1010 is merged, you can either rebase or just wait until someone with write access picks  it.

2020-03-06 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1009) <br/>All committers have signed the CLA.

2021-06-30 21:29 UTC, jpmcb requested changes
Hi @NickolasHKraus - thank you so much for the contribution!!

Looks like there is a conflict in the readme. Can you update and I'll get this in ASAP?

2021-11-02 13:58 UTC, jpmcb commented
Hi @NickolasHKraus - any chance we can get an update from you on this? Otherwise, I'll close this and open an issue to address this - thanks much

2021-11-02 17:19 UTC, NickolasHKraus commented
@jpmcb Sorry I missed your original message! Rebased and addressed merge conflicts

2021-11-02 17:45 UTC, umarcor approved these changes

2021-11-15 20:26 UTC, merged