Deprecate Go < 1.14
spf13/cobra pull request #1323
Opened 2021-01-29 03:38 UTC by jharshman

In accordance with our adopted best practices, the main branch and the
next major release of Cobra will deprecate older and un-maintained
versions of Golang.

fix #1322

2021-01-29 03:46 UTC, jharshman commented
@umarcor I would actually like to incorporate some of the changes from #1044. Namely the addition of golangci-lint and the fixes to the issues the linters surface.

Let me know how you would like to proceed with that PR.

2021-01-29 23:26 UTC, jpmcb requested changes
Does this also need changes in `go.mod`? I see 

```
 go 1.12
```

Will this need to be updated to 1.14?

2021-01-29 23:43 UTC, jharshman commented
@jpmcb good catch, yes that should be updated as well.

2021-01-29 23:56 UTC, umarcor commented
@jharshman, please, go ahead with this. I will then rebase and cleanup on top of master. Adding golangci-lint and so is not strictly related to this, but it will make it easier if I can focus on >1.11 features only. FTR, I did split the initial golangci-lint into two PRs so keep >1.11 features isolated. Now, both can be merged again, so I will close one of them.

2021-02-01 15:37 UTC, jpmcb approved these changes
Sweet - Thanks @jharshman looks good to me! 👍

2021-02-01 22:59 UTC, jharshman commented
Merging w/o latest CI run. TravisCI still queuing and takes forever. Seems to be related to their switch from .org to .com.

2021-02-01 22:59 UTC, merged

2021-02-02 00:05 UTC, umarcor commented
@jharshman, unfortunately, I don't think it's a transitory issue. The switch from .org to .com has been going on for 2-3 years. However, they recently changed their pricing model. Free resources for open source projects were significantly reduced, and maintainers need to periodically request additional "credits". Since this projects is in spf13's namespace, I guess that only he can see the state of the credits.

In practice, most open source projects are migrating from Travis CI to somewhere else, mostly GitHub Actions.

- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://github.com/python-pillow/Pillow/issues/5028
- https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works