Correcting Misspelled Words
spf13/cobra pull request #1349
Opened 2021-02-13 17:05 UTC by moritamori

2021-02-13 17:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1349) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cobra?pullRequest=1349) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cobra?pullRequest=1349) it.</sub>

2021-02-13 20:43 UTC, marckhouzam approved these changes
Thanks for this.

2021-02-13 20:43 UTC, marckhouzam commented on custom_completions.go
> +			// - there are no local, non-persistent flag on the command-line or TraverseChildren is true
Might as well put an 's' at 'flag' since we're correcting this sentence

2021-02-15 17:53 UTC, jpmcb requested changes
Hi @moritamori - can you rebase and get the latest changes I just merged from #1192 (which include a file name change)

Also, if you could include the changes suggested in #1350, that would be highly appreciated!

2021-02-16 02:01 UTC, moritamori commented
@jpmcb
Thank you for your feedback. 
I rebased this branch and inclueded the changes suggested in #1350.

2021-03-08 00:34 UTC, moritamori commented
@jpmcb 
Could you accept?

2021-05-10 23:19 UTC, jpmcb approved these changes
LGTM - thanks for the patience on this!! :rocket:

2021-05-10 23:19 UTC, merged