Prefer ReplaceAll instead of Replace(..., -1)
spf13/cobra pull request #1530
Opened 2021-11-08 19:22 UTC by WhyNotHugo

Minor change that gopls pointed out. I think it improves readability a bit.

2021-11-08 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1530) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cobra?pullRequest=1530) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cobra?pullRequest=1530) it.</sub>

2021-11-08 21:47 UTC, umarcor commented
According to https://pkg.go.dev/strings#ReplaceAll, `ReplaceAll` was added in go 1.12. I guess that's why it was not used before.  Nevertheless, 1.12 was EOL in Feb 2020, so I guess it's ok to introduce this change.

2021-11-08 21:48 UTC, umarcor approved these changes

2021-11-10 13:18 UTC, WhyNotHugo commented
Signing the DCO requires me to grant read-write access to all my gists, commit statuses and webhooks.

I'm okay with [the DCO](https://developercertificate.org/), and agree to its terms for this contributions.

However, I can't grant you write access to all my unrelated projects, I'm sure you'll understand that this doesn't make sense for an external contributor.

The wording above is also rather confusing; @CLAassistant here says I need to sign a CLA, and it says CLA everywhere on public pages, but the text I'm shown when trying to complete the flow is the DCO. I find it a bit discomforting that public content specifies one document, but the signing procedure displays another.

Maybe you want to consider using the this integration instead? -> https://github.com/apps/dco

2021-11-10 13:33 UTC, umarcor commented
@WhyNotHugo I understand your concerns, but unfortunately I cannot confirm.

On the one hand, I do not remember signing the CLA or DCO, however, in my PRs that check is shown green. Maybe it's the first contribution only and it then checks the list of previous contributors. Therefore, I'm not sure it is compulsory for your to sign it (use the app).

On the other hand, if I go to https://cla-assistant.io/spf13/cobra?pullRequest=1530 and I click "Sign in with Github to agree", I see the following:

![image](https://user-images.githubusercontent.com/38422348/141121916-a911321f-1a8a-4073-a101-aaef6d37b848.png)

I'm curious about why it's asking you read-write access to all the gists, commit statuses and webhooks.

> The wording above is also rather confusing; @CLAassistant here says I need to sign a CLA, and it says CLA everywhere on public pages, but the text I'm shown when trying to complete the flow is the DCO. I find it a bit discomforting that public content specifies one document, but the signing procedure displays another.
> 
> Maybe you want to consider using the this integration instead? -> https://github.com/apps/dco

I like this proposal. Maybe you can open an issue about it?

2021-11-10 14:05 UTC, WhyNotHugo commented
![image](https://user-images.githubusercontent.com/730811/141127292-a09d3336-d5b0-48c0-a6f6-4199ddc7af38.png)

Maybe it doesn't show up for you because you've already granted permissions? Yeah, I'll open up a separate issue on the topic :)

2021-11-10 14:10 UTC, umarcor commented
> Maybe it doesn't show up for you because you've already granted permissions?

Interesting... I checked my profile and that app is not found anywhere...

2021-12-07 23:10 UTC, jpmcb commented
Hmmmm @WhyNotHugo this is somewhat concerning. I had no idea the CLA / DCO required such wide permissions. Can you open a separate issue, include the screenshot, and a short description and we can ping Steve there?

2021-12-08 16:37 UTC, WhyNotHugo commented
See #1555.

2022-02-07 09:39 UTC, WhyNotHugo commented
Not stale

2022-03-17 22:16 UTC, marckhouzam commented
> According to https://pkg.go.dev/strings#ReplaceAll, `ReplaceAll` was added in go 1.12. I guess that's why it was not used before. Nevertheless, 1.12 was EOL in Feb 2020, so I guess it's ok to introduce this change.

What is the oldest version of Go that can be used with Cobra right now? Is it older than 1.12?

2022-03-17 23:45 UTC, umarcor commented
@marckhouzam we are testing 1.14 to 1.18 in CI. go.mod declares 1.15: https://github.com/spf13/cobra/blob/master/go.mod#L3.
Deprecating <1.14 was announced in January 2021: #1322. See https://github.com/spf13/cobra/blob/master/CONDUCT.md#backward-compatibility. So, we might announce that <1.17 will be deprecated in the next release.

2022-03-18 01:52 UTC, marckhouzam commented
> @marckhouzam we are testing 1.14 to 1.18 in CI. go.mod declares 1.15: https://github.com/spf13/cobra/blob/master/go.mod#L3. Deprecating <1.14 was announced in January 2021: #1322. 

Thanks @umarcor !

Ok, so using a construct from go 1.12 is perfectly fine.

@WhyNotHugo could you rebase this PR to the latest version of the master branch please?

2022-03-19 17:27 UTC, marckhouzam commented on bash_completions.go
> +	name = strings.ReplaceAll(name, ":", "__", )
The linter is failing.  I hadn't even noticed that the last comma preceding the `-1` was not removed.  This seems to be the case for almost every change 😄 

@WhyNotHugo could you please fix that? Thanks.

2022-03-29 23:14 UTC, jpmcb requested changes
This needs commas removed from the trailing `ReplaceAll` throughout. Commented on a few but there are others

Running `make lint` locally should be helpful!

2022-03-29 23:14 UTC, jpmcb commented on bash_completions.go
> +	commandName = strings.ReplaceAll(commandName, ":", "__", )
Extra commas here. Should it be?

```diff
- commandName = strings.ReplaceAll(commandName, ":", "__", )
+ commandName = strings.ReplaceAll(commandName, ":", "__")
```

2022-03-29 23:14 UTC, jpmcb commented on doc/man_docs.go
> +			dashParentPath := strings.ReplaceAll(parentPath, " ", "-", )
Extra commas here. Should it be?

```diff
- dashParentPath := strings.ReplaceAll(parentPath, " ", "-", )
+ dashParentPath := strings.ReplaceAll(parentPath, " ", "-")
```

2022-03-29 23:14 UTC, jpmcb commented on doc/man_docs_test.go
> +	return strings.ReplaceAll(in, "-", "\\-", )
Extra commas here. Should it be?

```diff
- return strings.ReplaceAll(in, "-", "\\-", )
+ return strings.ReplaceAll(in, "-", "\\-")
```

2022-03-29 23:14 UTC, jpmcb commented on doc/man_docs_test.go
> +	dashParentPath := strings.ReplaceAll(parentPath, " ", "-", )
Extra commas here. Should it be?

```diff
- dashParentPath := strings.ReplaceAll(parentPath, " ", "-", )
+ dashParentPath := strings.ReplaceAll(parentPath, " ", "-")
```

2022-04-04 12:46 UTC, marckhouzam approved these changes
Thanks @WhyNotHugo 
LGTM

I'll leave this for @jpmcb since he also started reviewing it.

2022-05-14 20:10 UTC, jpmcb approved these changes
LGTM!! Thanks so much for the patience on this one!!

2022-05-14 20:10 UTC, merged