fix some typos
spf13/cobra pull request #1625
Opened 2022-03-10 03:54 UTC by cuishuang

2022-03-10 03:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cobra?pullRequest=1625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cobra?pullRequest=1625) it.</sub>

2022-03-10 08:16 UTC, umarcor approved these changes
LGTM!

2022-03-10 20:12 UTC, marckhouzam commented
Thanks @cuishuang!  The `cobra/README.md` file has just moved to the `https://github.com/spf13/cobra-cli` repo.  You are welcomed to make a PR in that repo as well.

You will need to rebase your PR to remove that file.  Thanks!

2022-03-13 02:02 UTC, jpmcb requested changes
Go ahead and reabase since we've recently removed the `spf13/cobra/cobra` package. It's moved to [github.com/spf13/cobra-cli](github.com/spf13/cobra-cli)

For more info on this, check out: #1604 

Otherwise, this looks good!

2022-03-13 13:09 UTC, cuishuang commented
> 

Done. Sir, Do I need to merge several commits into one？

2022-03-14 11:05 UTC, merged