feat(completion): support no space format of short flags
spf13/cobra pull request #1727
Opened 2022-06-13 17:29 UTC by fiftin

Cobra supports a "no space" format for short flags but doesn't support auto complete for this case.
 
Related to issue https://github.com/spf13/cobra/issues/1629

2022-06-13 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cobra?pullRequest=1727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cobra?pullRequest=1727) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cobra?pullRequest=1727) it.</sub>

2022-06-13 19:33 UTC, marckhouzam commented
Supet exciting @fiftin !  I didn't expect it to be that simple 😁.  I'll give it a try ASAP 🚀

You will have to sign the CLA before we can accept the contribution however.

2022-06-13 20:01 UTC, fiftin commented
@marckhouzam ,

How to do this?

2022-06-14 01:51 UTC, marckhouzam commented
@fiftin I'm having trouble understanding what this change is supposed to provide.
Could you provide an example output of before and after the change please?

2022-06-14 06:19 UTC, fiftin commented
-f123<TAB>

Output

Before: Empty

After:

-f flag description

2022-06-14 12:01 UTC, marckhouzam commented
@fiftin Sorry but I'm still having trouble understanding the behaviour you seek.

If a program has a short flag `-f` like your example, and the user does:
`prog -f123<TAB>` why would the completion show `-f`?  And what is the `123` string; is it a value for `-f` or are they other short flags?

2022-06-14 19:44 UTC, marckhouzam commented
@fiftin 
So let's say the user currently does:
```
$ kubectl -n infra-pro<TAB>
# or
$ kubectl -n=infra-pro<TAB>
```
in both cases, the completion logic would suggest all namespaces that start with `infra-pro`, for example `infra-production1` and `infra-production2`.

I believe the same behaviour should happen when there is no space after the short flag.
```
$ kubectl -ninfra-pro<TAB>
infra-production1      infra-production2
```

But there are special cases we would need to treat differently:
```
$ kubectl -n<TAB>
# Should probably complete to -n

$ kubectl -itn<TAB>
# Should probably complete to -n because each letter 'i', 't', 'n' represent a valid short flag and the first two don't take an argument

$ kubectl -itni<TAB>
# Should probably complete to all namespaces starting with 'i' because the first letter 'i' and second letter 't', represent
# valid short flags not needing an argument, but the third letter 'n' represents a short flag that requires a namespace
# as an argument, so the forth letter 'i' no longer represents a flag but the prefix of a namespace name.
```

Does this make sense to you?

2022-06-16 10:43 UTC, fiftin commented
Hi @marckhouzam,

Done. Please see test `TestShorthandFlagCompletionInGoWithDesc` for details.

https://github.com/spf13/cobra/blob/87c16f9d0b2dccac2ca8911441cfe21f1ee52d17/completions_test.go#L476

2022-06-21 15:42 UTC, marckhouzam requested changes
This is a great start @fiftin, thanks!

Testing with a real program, the go logic to handle short flags without a space seems to work as expected.

I like your idea of checking if a completion function exists to decide if
we should complete a short flag value, or if we should add a space after
the short flag.

So, when testing with the __complete command things seem good nicely.

However when testing with the actual shell while performing completions
things don't work just yet.  For zsh for example, we need to set the variable `flagPrefix`
in the script.  What I mean is that if we do
```
$ helm -n<tab>
```
and get the completion choices 'firstns' and 'secondns', the zsh completion
script must convert them into '-nfirstns' and '-nsecondns'.  We already
do this for the = case:
```
$ helm -n=<tab>
firstns       secondns
```
So the zsh shell script would need to be modified a little to handle the new case
of completion of short flags.  The completion for bash v2 will also need
to be fixed (I haven't looked at the details, but it also does not work).  And we'll need to
try things out for fish and powershell to see what they need.  I can help
out with all this if you want, you just let me know.

But we are making good progress 👍

2022-06-21 16:11 UTC, fiftin commented on completions_test.go
> +func xTestDefaultCompletionCmd(t *testing.T) {
Hi @marckhouzam I did. I updated PR yesterday with --force flag

2022-06-26 19:51 UTC, fiftin commented
Hi @marckhouzam , any updates? What do you think about our issue?

2022-06-26 20:12 UTC, marckhouzam commented
Thanks @fiftin for the effort.  I will need to take the time to give this proper attention but I will not have time for the next couple of weeks.  I'll get back to this as soon as I can.  Thanks for your patience

2022-07-11 17:16 UTC, fiftin commented
Hi @marckhouzam ,

Do you have a time to work on the issue?

2022-08-01 06:24 UTC, closed without merging

2022-08-13 20:47 UTC, marckhouzam commented
@fiftin Are you no longer interested in making this contribution?  I was about to review it when I saw you had closed it.
I'm sorry it took a long time, but it is summer time and I was on vacation.