doc: Add CloudQuery for projects using Cobra
spf13/cobra pull request #1742
Opened 2022-06-23 16:55 UTC by yevgenypats

Hi 👋 

We are using Cobra so thought to add our project here for people's reference. We used to learn a lot from the examples here so thought to share back.

2022-06-23 21:05 UTC, marckhouzam requested changes
Thanks @yevgenypats! Great to see more cool projects using Cobra 🐍

You will need to sign the CLA before we can accept this contribution. Please see : https://github.com/spf13/cobra/pull/1742#issuecomment-1164651292

2022-06-24 16:16 UTC, yevgenypats commented
Not sure Im able to sign it with this link - https://cla-assistant.io/spf13/cobra?pullRequest=1742 maybe something is off there? or should I try again a bit later?

2022-06-24 20:20 UTC, yevgenypats commented
> Not sure Im able to sign it with this link - https://cla-assistant.io/spf13/cobra?pullRequest=1742 maybe something is off there? or should I try again a bit later?

Ok seems like the CLA was down :) signed now.

2022-06-24 20:22 UTC, yevgenypats commented on projects_using_cobra.md
> +- [CloudQuery](https://github.com/cloudquery/cloudquery)
Done

2022-06-25 16:17 UTC, merged

2022-06-27 10:06 UTC, umarcor commented
@marckhouzam please milestone this PR.