Add 'one required flag' group
spf13/cobra pull request #1952
Opened 2023-04-25 14:14 UTC by marevers

This PR addresses #1761 and #1891 - it adds a new flag group which can be used to group a set of flags of which at least one is required. If the related command is invoked and none of the flags in the group are set, the user is informed of the flag group (e.g. with two flags called 'path' and 'id'):

```
Error: at least one of the flags in the group [path id] is required
```

It is used like the other flag groups (MarkFlagsMutuallyExclusive / MarkFlagsRequiredTogether):

```
getCmd.AddCommand(getEntryCmd)
getEntryCmd.MarkFlagsOneRequired("path", "id")
```

It can also be combined with MarkFlagsMutuallyExclusive with the same set of flags to enforce only one flag (and not more than one).

Tests have not yet been added - I will add them if my suggested implementation is okay.

2023-06-11 14:47 UTC, marckhouzam reviewed
Thanks @marevers, this looks great.
I've added this to the planned features for the next release.

1. Add you mentioned, could you add some tests please?
2. Could you also update `enforceFlagGroupsForCompletion()`. I think what we need there is that: if none of the flags in the new required group are present, all of them should be marked as required so the completion suggests all of them, but as soon as one of them is present, we do nothing more.

2023-07-12 11:11 UTC, marckhouzam commented
Nicely done @marevers !  Thanks.
I want to run a bit more tests, but this should be ready to merge soon.

2023-07-12 19:08 UTC, marckhouzam reviewed
Everything is fine.
One last thing to ensure quality, can you also add a test like `TestCompletionForGroupedFlags` and `TestCompletionForMutuallyExclusiveFlags`
Then we can merge.

Thanks

2023-07-13 13:43 UTC, marckhouzam commented
@marevers Sorry for the confusion.  The `TestCompletionForGroupedFlags` and `TestCompletionForMutuallyExclusiveFlags` already exist in the `completions_test.go` file.  You can do something very similar for a new `TestCompletionForOneRequiredGroupFlags`

2023-07-14 06:36 UTC, marevers commented
@marckhouzam Thanks for the clarification. I added a new test function `TestCompletionForOneRequiredGroupFlags` based on `TestCompletionForGroupedFlags` with very similar subtests but also verifying that when any flag in the one-required group is present, other flags will not be suggested.

2023-07-14 16:16 UTC, marckhouzam approved these changes
LGTM
Thanks @marevers !

2023-07-14 16:19 UTC, marckhouzam commented
@marevers I was about to press merge, and then I remembered we need to update the doc.  It should be very quick for you.  Can you update this section please: https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#flag-groups

2023-07-15 07:47 UTC, marevers commented
@marckhouzam Okay, that should do it. I had to resync my fork because `user_guide.md` had been moved since I made that fork.

2023-07-15 12:05 UTC, marckhouzam requested changes
One typo and we're good to go.

2023-07-15 12:05 UTC, marckhouzam commented on site/content/user_guide.md
> +If you want to require least one flag from a group to be present, you can use `MarkFlagsOneRequired`.
```suggestion
If you want to require at least one flag from a group to be present, you can use `MarkFlagsOneRequired`.
```

2023-07-16 07:55 UTC, marevers commented
> One typo and we're good to go.

Fixed!

2023-07-16 16:36 UTC, marckhouzam approved these changes
LGTM
Thanks @marevers !
There’s already scenarios where this new feature can be used in the CLI I work on. This will be great!

2023-07-16 16:38 UTC, merged